### ISSUE TITLE
ssh/sshd_config conflict

### ISSUE THREAD

**Issue by pmsullivan85** [fcaviggia/hardening-script-el6#41]
The update of MACs in the sshd_config file are incompatible with the MAC specified in the ssh_config file:

[clipuser@vanilla Desktop]$ sudo grep MAC /etc/ssh/ssh*config
/etc/ssh/ssh_config:#   MACs hmac-md5,hmac-sha1,umac-64@openssh.com,hmac-ripemd160
/etc/ssh/ssh_config:MACs hmac-sha1
/etc/ssh/sshd_config:MACs hmac-sha2-512,hmac-sha2-256,hmac-ripemd160,hmac-sha1-96

So the client can only use hmac-sha1, while the server will only accept hmac-sha1-96 or better.
gen005512 seems to be quite dated - the intent was to force sha1 OR BETTER, but the implementation restricts it to ONLY hmac-sha1, which isnt good enough for the server, which now requires sha1-96 or better.

**Comment by pmsullivan85** [comment]
The wording of the gen005512 STIG unnecessarily restricts the HMAC - suggest the the MACs line in the ssh_config be updated to match that in the sshd_config file - so if sha1 isn't already in the ssh_config file, the added line should be:
MACs hmac-sha2-512,hmac-sha2-256,hmac-ripemd160,hmac-sha1-96

vice:
MACs hmac-sha1

**Comment by fcaviggia** [comment]
I think I'm going to just set it to the FIPS Standard:

Protocol 2
Ciphers aes128-ctr,aes192-ctr,aes256-ctr,aes128-cbc,3des-cbc,aes192-cbc,aes256-cbc
Macs hmac-sha1,hmac-sha2-256,hmac-sha2-512

https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/6/html/Security_Guide/sect-Security_Guide-Federal_Standards_And_Regulations-Federal_Information_Processing_Standard.html

**Comment by fcaviggia** [comment]
Set the configuration to the FIPS 140-2 standard. Closing issue.
