### ISSUE TITLE
SCAP score with STIG benchmark went down

### ISSUE THREAD

**Issue by jgr208** [fcaviggia/hardening-script-el6#44]
I ran a open scap scan with the benchmark files from a government website on an old version of these scripts with the kick start on RHEL 6.5 that was upgraded to 6.6 and got a 93% pass rate. I just did the same with the new version of the scripts with RHEL 6.6 iso and got a score of 78% pass rate. Is there any reason behind why this score might have gone down?

**Comment by Lukebrisk** [comment]
What benchmark did you test it against?  DISA?  V1R6?

**Comment by jgr208** [comment]
V1R6 were used to run for both, that is why I am not sure why the score would go down. https://web.nvd.nist.gov/view/ncp/repository/checklistDetail?id=438 is the scap files I got to run against.

**Comment by fcaviggia** [comment]
I'll try to do some testing this weekend - quick question did you use the kickstart for the install?  It does a few more items like partitioning and classification banner.

**Comment by jgr208** [comment]
Sorry for the late reply @fcaviggia but yes I did use the kickstart for the install.

**Comment by fcaviggia** [comment]
I'll try to do some more testing later - I've been a bit swamped with customer work for Red Hat. I'll hit this again tonight.

**Comment by jgr208** [comment]
I actually edited some of the files on a fork to now get it up to an almost 100% score but these are not applicable to all systems for hardening only DISA, as in the password must be 14 characters instead of 12 and other things like that. So I would consider this closed and fixed with anyone wishing to loop at DISA specific lockdowns to look at my fork.
