### ISSUE TITLE
Unable to use PuTTy

### ISSUE THREAD

**Issue by jlamb85** [fcaviggia/hardening-script-el6#45]
I am unable to use PuTTy to ssh to new built server...Is there a reason??

**Comment by fcaviggia** [comment]
Putty doesn't fully comply with FIPS 140-2 compliant  MACs setting in SSH (/etc/ssh/sshd_config) you might add on hmac-sha1-96 to work around the problem. Let me know if that works.

**Comment by jlamb85** [comment]
hmac-sha1-96 was already in the sshd_config.

**Comment by fcaviggia** [comment]
Try hmac-sha1 or pull the latest version of the sshd configuration:

    https://github.com/fcaviggia/hardening-script-el6/blob/master/config/sshd_config

What version of putty? I'll try to reproduce it later this evening.

**Comment by amlozano1** [comment]
I am using putty .63 and also can't connect. 

/var/log/secure says:
ssh[32808]: Failed password for (MyUser) from (My_ip) port (some Port) ssh2 

It was also complaining about bad permissions on /var/log/btmp, so I changed those from 640 to 600 and it stopped complaining.

**Comment by amlozano1** [comment]
I take this back, after following you instructions to add a remote user with

`useradd -m -c "Remote User" -G sshusers remoteuser`

The user was able to log in through SSH with Putty just fine. It seems I did something wrong in migrating over my existing user account.

**Comment by fcaviggia** [comment]
Yeah, the 'sshusers' group was basically a way to differentiate between local (console only) and remote users.  It's the same thing with the wheel group - you can't be an privileged user (sudo preferred over su) without that group. Sorry for the misunderstanding.

**Comment by jlamb85** [comment]
I have the user in the sshusers and wheel group and as soon as I login the system disconnects me.  Any Ideas??
