### ISSUE TITLE
From SSH can't su -

### ISSUE THREAD

**Issue by jlamb85** [fcaviggia/hardening-script-el6#46]
I am unable to su from general user to root.  I am sure it is a setting somewhere but have not found it.  If you know where it is please advise.  Thanks

**Comment by fcaviggia** [comment]
Yep. Part of the the guide - you need to be a member of the wheel group - sudo is prefered.

**Comment by jlamb85** [comment]
Added user to wheel group and now getting the following

sudo: effective uid is not 0, is sudo installed setuid root?

my /usr/bin/sudo has the following permissions

---s--x--x. 1 root root 123832 Oct  7  2013 /usr/bin/sudo

**Comment by necrolyte2** [comment]
Adding the user to the wheel group only allows you to use the ``su`` command

In order to use sudoers with all users in the wheel group uncomment the following line in ``/etc/sudoers``

``# %wheel    ALL=(ALL)   ALL``

**Comment by lmeinecke** [comment]
http://www.stigviewer.com/stig/red_hat_enterprise_linux_5/2014-07-07/finding/V-22308?

This is for RHEL5 but it applies to RHEL6. This is what is driving the requirement and where it is applied in pam.d



?Lee Meinecke, CISSP

Research Associate

Georgia Tech Research Institute

Applied Systems Laboratory

Phone: 256-513-9420

________________________________

**Comment by jlamb85** [comment]
I would rather use sudo but I get the an error

sudo: effective uid is not 0, is sudo installed setuid root?

**Comment by jlamb85** [comment]
This line is uncommented
%wheel ALL=(ALL) ALL

**Comment by necrolyte2** [comment]
Can you also verify that the sudo executable that is in your path is ``/usr/bin/sudo``

``which sudo``
``ls -l $(which sudo)``

The permissions look correct on /usr/bin/sudo and should work fine

**Comment by necrolyte2** [comment]
Looks like most likely this is the cause

**Comment by jlamb85** [comment]
which sudo = /usr/bin/sudo from the user not root

**Comment by necrolyte2** [comment]
Is /usr mounted with nosuid?

``cat /proc/mounts | grep '/usr'``

**Comment by jlamb85** [comment]
Yes /usr had nosuid   Thanks all
