### ISSUE TITLE
scripts/gen001260.sh follows RHEL5 stig, not RHEL6 stig

### ISSUE THREAD

**Issue by jpschaaf** [fcaviggia/hardening-script-el6#50]
The RHEL-06-000135 STIG entry requires that log files in /var/log have permissions of 600, not 640 (except for cases where the log file has a specific need for more liberal permissions).  

gen001260.sh should be revised accordingly.

**Comment by fcaviggia** [comment]
Thanks for the update - changed accordingly under the following commit:

https://github.com/fcaviggia/hardening-script-el6/commit/e8aa39db148e35395993c2347e05ea03931c0c27
