### ISSUE TITLE
SSH from linux client to hardening server

### ISSUE THREAD

**Issue by jlamb85** [fcaviggia/hardening-script-el6#53]
I am still having problems with ssh'ing from a client that has openssh-5.3p1-104.el6_6.1 going to a hardening server using openssh-server-5.3p1-104.el6_6.1.  I have used ssh -c aes256-ctr hostip and am unable to ssh.  Do I need to specify the allowed host or allowed users in the sshd_config on the server?

**Comment by jlamb85** [comment]
BTW: user is in sshusers and wheel group

**Comment by fcaviggia** [comment]
Have you tried to re-base your /etc/pam.d/sshd_config with the one here:

   https://raw.githubusercontent.com/fcaviggia/hardening-script-el6/master/config/sshd_config

I'm curious if you could diff your current config to that one?

-Frank

**Comment by jlamb85** [comment]
Haven't done that yet. I will try it
