### ISSUE TITLE
Added user but unable to ssh

### ISSUE THREAD

**Issue by jlamb85** [fcaviggia/hardening-script-el6#61]
Added a new user (ia_admin) and I am unable to ssh as this user.  Please help

Results from grep on all files in /etc for ia_admin

/etc/group:wheel:x:10:user1,ia_admin
/etc/group:sshusers:x:501:user1,ia_admin
/etc/group:isso:x:502:ia_admin
/etc/group:ia_admin:x:503:
/etc/gshadow:wheel:::ia_admin
/etc/gshadow:sshusers:!::ia_admin
/etc/gshadow:isso:!::ia_admin
/etc/gshadow:ia_admin:!::
/etc/passwd:ia_admin:x:501:503:IA Admin:/home/ia_admin:/bin/bash
/etc/shadow:ia_admin:$6$dqYmgQuT$g9kg8WFvctxf5GdlSaDPx87jw6MDmL8PNDWQCMGv3EVMmxH/M5keR1jAguAH4mFstrf527mm/TJ/DtzjoTT121:16745:1:60:7:::

The :x: is : x : without the spaces

Used the following command to add user
useradd -m -c "Remote User" -G sshusers,isso,wheel ia_admin

**Comment by jlamb85** [comment]
The :x: is : x : without the spaces

**Comment by jlamb85** [comment]
Used the following command to add user
useradd -m -c "Remote User" -G sshusers,isso,wheel ia_admin

**Comment by fcaviggia** [comment]
What does your /etc/ssh/sshd_config and /etc/pam.d/password-auth file look like? Also, the ISSO user is a subset (read any file) of wheel (admin) user...

**Comment by jlamb85** [comment]
I don't have an ISSO user but have an ISSO group.

/etc/pam.d/password-auth
#%PAM-1.0
#
# pam.d/system-auth - PAM master configuration for CAPP/LSPP compliance
#		see the Evaluated Configuration Guide for more info
#
auth        required      pam_env.so
auth	      required      pam_lastlog.so inactive=35
auth        required      pam_faillock.so preauth silent audit deny=3 even_deny_root root_unlock_time=900 unlock_time=604800 fail_interval=900
auth        sufficient    pam_unix.so try_first_pass
auth        [default=die] pam_faillock.so authfail audit deny=3 even_deny_root root_unlock_time=900 unlock_time=604800 fail_interval=900
auth        sufficient    pam_faillock.so authsucc audit deny=3 even_deny_root root_unlock_time=900 unlock_time=604800 fail_interval=900
auth        requisite     pam_succeed_if.so uid >= 500 quiet
auth        required      pam_deny.so

account     required      pam_unix.so
account     required      pam_faillock.so
account	    required      pam_lastlog.so inactive=35
account     sufficient    pam_localuser.so
account     sufficient    pam_succeed_if.so uid < 500 quiet
account     required      pam_permit.so

#password    required      pam_passwdqc.so min=disabled,disabled,16,12,8 random=42
password    required      pam_cracklib.so retry=3 minlen=14 dcredit=-1 ucredit=-1 ocredit=-1 lcredit=-1 difok=4
password    sufficient    pam_unix.so sha512 shadow try_first_pass use_authtok remember=24
password    required      pam_deny.so

session     required      pam_lastlog.so showfailed
session     optional      pam_keyinit.so revoke
session     required      pam_limits.so
session     [success=1 default=ignore] pam_succeed_if.so service in crond quiet use_uid
session     required      pam_unix.so
------------------------------------------------------------------------------------------------------------------------
/etc/ssh/sshd_config 
#	$OpenBSD: sshd_config,v 1.80 2008/07/02 02:24:18 djm Exp $

# This is the sshd server system-wide configuration file.  See
# sshd_config(5) for more information.

# This sshd was compiled with PATH=/usr/local/bin:/bin:/usr/bin

# The strategy used for options in the default sshd_config shipped with
# OpenSSH is to specify options with their default value where
# possible, but leave them commented.  Uncommented options change a
# default value.

#Port 22
#AddressFamily any
ListenAddress 192.168.240.107
#ListenAddress ::

# Disable legacy (protocol version 1) support in the server for new
# installations. In future the default will change to require explicit
# activation of protocol 1
Protocol 2

# HostKey for protocol version 1
#HostKey /etc/ssh/ssh_host_key
# HostKeys for protocol version 2
#HostKey /etc/ssh/ssh_host_rsa_key
#HostKey /etc/ssh/ssh_host_dsa_key

# Lifetime and size of ephemeral version 1 server key
#KeyRegenerationInterval 1h
#ServerKeyBits 1024

# Logging
# obsoletes QuietMode and FascistLogging
#SyslogFacility AUTH
SyslogFacility AUTHPRIV
LogLevel INFO

# Authentication:
AllowGroups sshusers
LoginGraceTime 2m
PermitRootLogin no
StrictModes yes
MaxAuthTries 3
MaxSessions 3

#RSAAuthentication yes
#PubkeyAuthentication yes
#AuthorizedKeysFile	.ssh/authorized_keys
#AuthorizedKeysCommand none
#AuthorizedKeysCommandRunAs nobody

# For this to work you will also need host keys in /etc/ssh/ssh_known_hosts
#RhostsRSAAuthentication no
# similar for protocol version 2
HostbasedAuthentication no
# Change to yes if you don't trust ~/.ssh/known_hosts for
# RhostsRSAAuthentication and HostbasedAuthentication
#IgnoreUserKnownHosts no
# Don't read the user's ~/.rhosts and ~/.shosts files
IgnoreRhosts yes

# To disable tunneled clear text passwords, change to no here!
#PasswordAuthentication yes
PermitEmptyPasswords no
PasswordAuthentication yes

# Change to no to disable s/key passwords
#ChallengeResponseAuthentication yes
ChallengeResponseAuthentication no

# Kerberos options
#KerberosAuthentication no
#KerberosOrLocalPasswd yes
#KerberosTicketCleanup yes
#KerberosGetAFSToken no
#KerberosUseKuserok yes

# GSSAPI options
#GSSAPIAuthentication no
GSSAPIAuthentication no
#GSSAPICleanupCredentials yes
GSSAPICleanupCredentials yes
#GSSAPIStrictAcceptorCheck yes
#GSSAPIKeyExchange no

# Set this to 'yes' to enable PAM authentication, account processing, 
# and session processing. If this is enabled, PAM authentication will 
# be allowed through the ChallengeResponseAuthentication and
# PasswordAuthentication.  Depending on your PAM configuration,
# PAM authentication via ChallengeResponseAuthentication may bypass
# the setting of "PermitRootLogin without-password".
# If you just want the PAM account and session checks to run without
# PAM authentication, then enable this but set PasswordAuthentication
# and ChallengeResponseAuthentication to 'no'.
#UsePAM no
UsePAM yes

# Accept locale-related environment variables
AcceptEnv LANG LC_CTYPE LC_NUMERIC LC_TIME LC_COLLATE LC_MONETARY LC_MESSAGES
AcceptEnv LC_PAPER LC_NAME LC_ADDRESS LC_TELEPHONE LC_MEASUREMENT
AcceptEnv LC_IDENTIFICATION LC_ALL LANGUAGE
AcceptEnv XMODIFIERS

#AllowAgentForwarding yes
#AllowTcpForwarding yes
GatewayPorts no
X11Forwarding no
#X11Forwarding yes
#X11DisplayOffset 10
#X11UseLocalhost yes
#PrintMotd yes
PrintLastLog yes
#TCPKeepAlive yes
#UseLogin no
UsePrivilegeSeparation yes
PermitUserEnvironment no
#Compression delayed
ClientAliveInterval 900
ClientAliveCountMax 0
#ShowPatchLevel no
#UseDNS yes
#PidFile /var/run/sshd.pid
#MaxStartups 10
#PermitTunnel no
#ChrootDirectory none

# no default banner path
Banner /etc/issue

# override default of no subsystems
Subsystem	sftp	/usr/libexec/openssh/sftp-server

# Example of overriding settings on a per-user basis
#Match User anoncvs
#	X11Forwarding no
#	AllowTcpForwarding no
#	ForceCommand cvs server
# Added for DISA GEN005538
RhostsRSAAuthentication no
# Added for DISA GEN005539
Compression delayed
# Added for DISA GEN005526
KerberosAuthentication no
# FIPS 140-2 Encryption
Ciphers aes128-ctr,aes192-ctr,aes256-ctr
Macs hmac-sha2-512,hmac-sha2-256,hmac-sha1

**Comment by jlamb85** [comment]
So if I add a user to the ISSO group they will be able to read each file on the filesystem??

/etc/pam.d/password-auth file without comments
auth        required      pam_env.so
auth          required      pam_lastlog.so inactive=35
auth        required      pam_faillock.so preauth silent audit deny=3 even_deny_root root_unlock_time=900 unlock_time=604800 fail_interval=900
auth        sufficient    pam_unix.so try_first_pass
auth        [default=die] pam_faillock.so authfail audit deny=3 even_deny_root root_unlock_time=900 unlock_time=604800 fail_interval=900
auth        sufficient    pam_faillock.so authsucc audit deny=3 even_deny_root root_unlock_time=900 unlock_time=604800 fail_interval=900
auth        requisite     pam_succeed_if.so uid >= 500 quiet
auth        required      pam_deny.so

account     required      pam_unix.so
account     required      pam_faillock.so
account     required      pam_lastlog.so inactive=35
account     sufficient    pam_localuser.so
account     sufficient    pam_succeed_if.so uid < 500 quiet
account     required      pam_permit.so

#password    required      pam_passwdqc.so min=disabled,disabled,16,12,8 random=42
password    required      pam_cracklib.so retry=3 minlen=14 dcredit=-1 ucredit=-1 ocredit=-1 lcredit=-1 difok=4
password    sufficient    pam_unix.so sha512 shadow try_first_pass use_authtok remember=24
password    required      pam_deny.so

session     required      pam_lastlog.so showfailed
session     optional      pam_keyinit.so revoke
session     required      pam_limits.so
session     [success=1 default=ignore] pam_succeed_if.so service in crond quiet use_uid
session     required      pam_unix.so
--------------------------------------------------------------------------------------------------------------
/etc/ssh/sshd_config without comments

Protocol 2
SyslogFacility AUTHPRIV
LogLevel INFO
AllowGroups sshusers
LoginGraceTime 2m
PermitRootLogin no
StrictModes yes
MaxAuthTries 3
MaxSessions 3
HostbasedAuthentication no
IgnoreRhosts yes
PermitEmptyPasswords no
PasswordAuthentication yes
ChallengeResponseAuthentication no
GSSAPIAuthentication no
GSSAPICleanupCredentials yes
UsePAM yes
AcceptEnv LANG LC_CTYPE LC_NUMERIC LC_TIME LC_COLLATE LC_MONETARY LC_MESSAGES
AcceptEnv LC_PAPER LC_NAME LC_ADDRESS LC_TELEPHONE LC_MEASUREMENT
AcceptEnv LC_IDENTIFICATION LC_ALL LANGUAGE
AcceptEnv XMODIFIERS
GatewayPorts no
X11Forwarding no
PrintLastLog yes
UsePrivilegeSeparation yes
PermitUserEnvironment no
ClientAliveInterval 900
ClientAliveCountMax 0
Banner /etc/issue
Subsystem	sftp	/usr/libexec/openssh/sftp-server
RhostsRSAAuthentication no
Compression delayed
KerberosAuthentication no
Ciphers aes128-ctr,aes192-ctr,aes256-ctr
Macs hmac-sha2-512,hmac-sha2-256,hmac-sha1

**Comment by jlamb85** [comment]
I think it was because of the underscore in the user name.  Fixed
