### ISSUE TITLE
Unable to update initscripts

### ISSUE THREAD

**Issue by jlamb85** [fcaviggia/hardening-script-el6#62]
When I try to update initscripts I get the following.  Any ideas on a way to fix this??

yum update
Loaded plugins: product-id, security, subscription-manager
This system is not registered to Red Hat Subscription Management. You can use subscription-manager to register.
Setting up Update Process
rhel-dvd                                                                                                                                                                     | 3.6 kB     00:00 ... 
rhel-dvd/primary_db                                                                                                                                                          | 6.0 MB     00:00 ... 
Resolving Dependencies
--> Running transaction check
---> Package initscripts.x86_64 0:9.03.40-2.el6 will be updated
---> Package initscripts.x86_64 0:9.03.49-1.el6_7.1 will be an update
--> Finished Dependency Resolution

Dependencies Resolved
# 

 Package                                        Arch                                      Version                                                 Repository                                   Size
# 

Updating:
 initscripts                                    x86_64                                    9.03.49-1.el6_7.1                                       rhel-dvd                                    945 k

Transaction Summary
# 

Upgrade       1 Package(s)

Total download size: 945 k
Is this ok [y/N]: y
Downloading Packages:
Running rpm_check_debug
Running Transaction Test
Transaction Test Succeeded
Running Transaction
/var/tmp/rpm-tmp.kHNVeK: line 1: /usr/sbin/groupadd: Permission denied
error: %pre(initscripts-9.03.49-1.el6_7.1.x86_64) scriptlet failed, exit status 126
Error in PREIN scriptlet in rpm package initscripts-9.03.49-1.el6_7.1.x86_64
error:   install: %pre scriptlet failed (2), skipping initscripts-9.03.49-1.el6_7.1
initscripts-9.03.40-2.el6.x86_64 was supposed to be removed but is not!
  Verifying  : initscripts-9.03.40-2.el6.x86_64                                                                                                                                                 1/2 
  Verifying  : initscripts-9.03.49-1.el6_7.1.x86_64                                                                                                                                             2/2 

Failed:
  initscripts.x86_64 0:9.03.40-2.el6                                                             initscripts.x86_64 0:9.03.49-1.el6_7.1                                                            

Complete!

**Comment by lmeinecke** [comment]
/var/tmp/rpm-tmp.kHNVeK: line 1: /usr/sbin/groupadd: Permission denied

This is the problem I suspect. Check the permissions on these files.

Sent from mobile

On Nov 10, 2015, at 5:57 AM, jlamb85 <notifications@github.com<mailto:notifications@github.com>> wrote:


When I try to update initscripts I get the following. Any ideas on a way to fix this??

yum update
Loaded plugins: product-id, security, subscription-manager
This system is not registered to Red Hat Subscription Management. You can use subscription-manager to register.
Setting up Update Process
rhel-dvd | 3.6 kB 00:00 ...
rhel-dvd/primary_db | 6.0 MB 00:00 ...
Resolving Dependencies
--> Running transaction check
---> Package initscripts.x86_64 0:9.03.40-2.el6 will be updated
---> Package initscripts.x86_64 0:9.03.49-1.el6_7.1 will be an update
--> Finished Dependency Resolution

Dependencies Resolved

Package Arch Version Repository Size

Updating:
initscripts x86_64 9.03.49-1.el6_7.1 rhel-dvd 945 k

Transaction Summary

Upgrade 1 Package(s)

Total download size: 945 k
Is this ok [y/N]: y
Downloading Packages:
Running rpm_check_debug
Running Transaction Test
Transaction Test Succeeded
Running Transaction
/var/tmp/rpm-tmp.kHNVeK: line 1: /usr/sbin/groupadd: Permission denied
error: %pre(initscripts-9.03.49-1.el6_7.1.x86_64) scriptlet failed, exit status 126
Error in PREIN scriptlet in rpm package initscripts-9.03.49-1.el6_7.1.x86_64
error: install: %pre scriptlet failed (2), skipping initscripts-9.03.49-1.el6_7.1
initscripts-9.03.40-2.el6.x86_64 was supposed to be removed but is not!
Verifying : initscripts-9.03.40-2.el6.x86_64 1/2
Verifying : initscripts-9.03.49-1.el6_7.1.x86_64 2/2

Failed:
initscripts.x86_64 0:9.03.40-2.el6 initscripts.x86_64 0:9.03.49-1.el6_7.1

Complete!

-

**Comment by jlamb85** [comment]
That is all well and good.  This is a temp file and disappears after it tries to update and fails.

**Comment by lmeinecke** [comment]
Does groupadd function normally on this host?

On Nov 12, 2015, at 5:28 AM, jlamb85 <notifications@github.com<mailto:notifications@github.com>> wrote:


That is all well and good. This is a temp file and disappears after it tries to update and fails.

-

**Comment by jlamb85** [comment]
Yes. groupadd does function normal.  I think it may have something to do with the STIG & initscripts.  I am able to update if I am in single user mode

**Comment by fcaviggia** [comment]
Try 'yum upgrade' instead of 'yum update' - I think I ran into this problem a bit ago.

**Comment by jlamb85** [comment]
Even with doing an upgrade instead of a update I get the same error
Error in PREIN scriptlet in rpm package initscripts-9.03.49-1.el6_7.2.x86_64
/var/tmp/rpm-tmp.H0FPbM: line 1: /usr/sbin/groupadd: Permission denied
error: %pre(initscripts-9.03.49-1.el6_7.2.x86_64) scriptlet failed, exit status 126
error:   install: %pre scriptlet failed (2), skipping initscripts-9.03.49-1.el6_7.2
  Updating   : udev-147-2.63.el6.x86_64                                                                                                                                                                                              217/635 
/var/tmp/rpm-tmp.FSiRVN: line 13: /sbin/udevadm: Permission denied
/var/tmp/rpm-tmp.ChtIAQ: line 4: /sbin/udevd: Permission denied
/var/tmp/rpm-tmp.ChtIAQ: line 5: /sbin/udevadm: Permission denied


Is there anyway to upgrade on install?

**Comment by stephenwb** [comment]
This sounds like tmpfs and/or /var, /var/tmp is mounted noexec and/or nosuid, so the script in /var/tmp/ can't run. Change/remove that mount option in /etc/fstab and do 'mount -a -o remount' and try the update again.

**Comment by johncolley** [comment]
I have had the same exact issue in my environment, Auditd and or HBSS where causing the issue for me. 
Originally, I only saw the issue during kernel updates and stopping auditd was the solution.
Unfortunately, as of lately anyway, the only solution is to remove HBSS, disable auditd(habit now), then perform updates.
I need to make the changes suggested in another post here to auditd (b=????)
