### ISSUE TITLE
Panic after update and reboot

### ISSUE THREAD

**Issue by jlamb85** [fcaviggia/hardening-script-el6#64]
I get a system panic after I update files with yum update and then reboot.  Is there  a certain way to update????

**Comment by stephenwb** [comment]
What RHEL version?
What packages updated? Any besides the hardening?
What is the exact panic message?

**Comment by jlamb85** [comment]
RHEL6.5
A lot of rpms needed to be and was updated to include initscript
Unable to find due to had to rebuild

**Comment by jlamb85** [comment]
Will submit new issue
