### ISSUE TITLE
Security Updates

### ISSUE THREAD

**Issue by jlamb85** [fcaviggia/hardening-script-el6#67]
When I update my system and reboot I get a PANIC condition.  Is there a certain way to do update other that yum update from the repo I created??

**Comment by fcaviggia** [comment]
I've seen that happen with the audit buffer being overrun - look at the '-b' setting in the audit.rules. I've also included the format for a local repo in the /etc/yum.repos.d/rhel-dvd.repo to update locally.

**Comment by jlamb85** [comment]
Thanks.  I will look at that

**Comment by jlamb85** [comment]
I have the following entry in my audit.conf

# Increase kernel buffer size
-b 8192

What does it suppose to be??

**Comment by fcaviggia** [comment]
You can try 16384 or 32768 to increase the buffer - I've had to do that for some systems depending on the rate at what is being audited the '-f 2' is what causes the kernel panic.
