### ISSUE TITLE
Question about CIS-CAT applicability

### ISSUE THREAD

**Issue by jpschaaf** [fcaviggia/hardening-script-el6#74]
This is more of a question than an issue, but what are your thoughts about updating these scripts to also target the CIS-CAT benchmark for RHEL 6?  

I can't claim that I'd be willing to do all of the work, but there's some low-hanging fruit that would dramatically increase the "score" given by XCCDF-based tools that use CIS-CAT as the baseline.  

Specifically, the CIS-CAT xccdf file has some really picky pattern matching on keys in the audit config file.  A few tweaks to key names could probably "fix" 10-15 items reported by their tool.  I'd also be adding a few more files to watch in the audit config file. 

Thoughts?

**Comment by fcaviggia** [comment]
This set of scripts is becoming depreciated - SCAP Security Guide (SSG)/OpenSCAP and Chef seem to be the way to go forward. You are welcome to for the scripts to meet your own needs (which is why I left them out there).

**Comment by fcaviggia** [comment]
DISA STIG and ICD503 (NIST 800-53 controls) were the aim of this project originally.

**Comment by jpschaaf** [comment]
Good to know you consider this approach outdated.  I still have my own selfish reasons to use shell scripts instead of Chef, so I'm going to continue going through the latest version of the STIG and updating these scripts.  I'll try to batch everything into one or two giant pull requests so you don't get hammered with every little item that I update.
